/* sl-atlas concept content — embedded for zero-build deployment.
   The same content is mirrored as JSON under ../content/ for tooling. */

window.SL_ATLAS_CONCEPTS = [
  {
    id: "lwe",
    title: "Learning With Errors",
    subtitle: "The hard problem at the heart of lattice cryptography",
    category: "foundations",
    views: {
      simple:
        "A puzzle made hard by adding small mistakes. Imagine someone hands you lots of almost-right answers to a math problem — each one off by a tiny, unknown nudge. With enough nudges, working backwards to the secret becomes practically impossible. That deliberate imperfection is the lock. Take it away and the puzzle dissolves into something a calculator could solve. This single idea — *make the linear problem noisy* — is the engine behind a whole family of post-quantum cryptography.",
      developer:
        "A linear system with noise added. You publish `(A, b)` where `b = A·s + e (mod q)`. `A` is a public random matrix. `s` is the secret vector. `e` is small random noise drawn from a bounded distribution. Recovering `s` from `(A, b)` is the hard problem your security rests on. **Strip the noise away** and it collapses to ordinary linear algebra — Gaussian elimination solves it in milliseconds. The noise is the lock; the modulus `q` sets the room the math lives in; the dimension `n` sets the difficulty.",
      researcher:
        "Given samples `(A, A·s + e mod q)` with `A ∈ Z_q^{m×n}` uniform, secret `s ∈ Z_q^n`, and error `e` drawn from a bounded distribution `χ`, recover `s`. **Decisional-LWE** asks instead to distinguish such samples from uniform over `Z_q^{m×n} × Z_q^m`. Hardness is parameterized by `(n, q, χ)`; concrete security estimates derive from the best known lattice-reduction (BKZ, sieving) and combinatorial (BKW, dual) attacks against those parameters. Worst-case to average-case reductions (Regev '05; Peikert '09; BLP+ '13) connect LWE to standard lattice problems (GapSVP, SIVP) under appropriate parameter regimes — a structural argument for confidence, not a proof of unbreakability."
    },
    interactive: "lwe-matrix",
    evidence_grade: "B",
    evidence_note:
      "Strong consensus across the lattice-crypto literature; the worst-case-to-average-case reductions are well-studied. Concrete security depends on continued cryptanalysis of the assumed parameters — graded 'strong evidence, not proven here.'",
    related: ["lattices", "noise", "modular"],
    citations: ["regev-2005", "peikert-2009", "blprs-2013"],
    source_spec: "../../sl-kem/spec/EXPLAINER-LWE.md"
  },
  {
    id: "lattices",
    title: "Lattices",
    subtitle: "Grids of points in high-dimensional space — and why they are hard",
    category: "foundations",
    views: {
      simple:
        "Imagine an infinite sheet of graph paper. The grid points are a *lattice* — a regular, evenly-spaced pattern of dots. Now imagine that same grid in three dimensions. Then in four hundred. The dots are still perfectly regular, but the patterns are no longer something you can picture. Find the dot nearest to a given target in 400 dimensions and you have just solved a problem that protects messages from quantum computers. The simplicity of the picture is what makes the difficulty so surprising: nothing about a grid *looks* hard, until the dimensions stack up.",
      developer:
        "A lattice is the set of all integer combinations of a fixed *basis* of vectors: `L = { a₁·b₁ + a₂·b₂ + … + aₙ·bₙ : aᵢ ∈ Z }`. Same lattice, different bases — and the difference matters: a *good* (short, near-orthogonal) basis makes problems easy, a *bad* (long, skewed) basis makes them hard. The public key in a lattice scheme is effectively a bad basis; the private key is a good one. The two canonical hard problems: **SVP** (shortest vector) and **CVP** (closest vector). Approximate versions of these, in high dimensions, are what concrete crypto rests on.",
      researcher:
        "A full-rank lattice `L ⊂ R^n` is a discrete additive subgroup generated by a basis `B = (b₁, …, bₙ)`. **SVP_γ**: given `B`, find `v ∈ L \\ {0}` with `‖v‖ ≤ γ · λ₁(L)`. **CVP_γ**: given `B` and target `t`, find `v ∈ L` with `‖v − t‖ ≤ γ · dist(t, L)`. **GapSVP_γ** and **SIVP_γ** are the standard worst-case problems used in reductions. The state-of-the-art attacks are BKZ-style block reduction with sieving subroutines; security estimates are produced by *lattice estimators* (e.g. the LWE-estimator), not by closed-form proofs. The cryptographic story: LWE-hardness reduces (worst-case to average-case) to GapSVP/SIVP, giving structural — not numerical — confidence."
    },
    evidence_grade: "A",
    evidence_note:
      "The mathematical definitions are standard and uncontested. The cryptographic hardness assumptions (GapSVP, SIVP at the parameter regimes we use) are well-studied but, like all hardness assumptions, not proven.",
    related: ["lwe", "noise"],
    source_spec: null
  },
  {
    id: "noise",
    title: "Noise",
    subtitle: "Small, deliberate imperfection — the cryptographic raw material",
    category: "foundations",
    views: {
      simple:
        "Noise here doesn't mean sound. It means a tiny random nudge added on purpose. In daily life, noise is the enemy — it makes signals harder to read. In lattice cryptography, noise is the *friend*: it is what makes the math hard for an attacker. The trick is to add just enough noise to lose the attacker, but not so much that the legitimate decoder cannot still recover the message. This careful balance — *enough but not too much* — is what most of the engineering in a scheme like Kyber is really about.",
      developer:
        "Noise is sampled from a bounded distribution `χ` (usually centered binomial or discrete Gaussian) and added to the equation `b = A·s + e`. The standard deviation `σ` is the central knob. Bigger `σ` → harder for an attacker, but also more *decryption failures*: legitimate decoders use an error-correcting structure to absorb the noise, and if `e` ever exceeds the absorption budget, decryption silently produces the wrong message. Modern schemes (Kyber, Saber, FrodoKEM) tune `(n, q, σ)` so that the decryption-failure probability is astronomically small (e.g. `≤ 2⁻¹⁶⁰`) *and* the LWE problem remains hard.",
      researcher:
        "Let `χ` be a discrete distribution over `Z` with sub-Gaussian parameter `σ`. The LWE distribution is `{(a, ⟨a,s⟩ + e mod q) : a ← U(Z_q^n), e ← χ}`. The relevant trade-off space is bounded by two constraints: (1) the *attacker's* problem must remain hard, formalized via lattice-estimator output against BKZ/sieving with cost models like `core-SVP`; (2) the *decoder's* failure probability `Pr[‖e_total‖_∞ > q/4]` (for a rounding-style decoder) must satisfy the cryptanalytic bound from decryption-failure attacks (D'Anvers et al., 2019). Choosing `χ` as a centered binomial `CBD_η` is preferred for constant-time sampling — Gaussian-discrete sampling has historically been a side-channel hazard."
    },
    evidence_grade: "B",
    evidence_note:
      "Mature engineering; concrete failure-probability bounds are well-understood. The 'enough noise / not too much' trade-off is actively re-evaluated as new attacks appear.",
    related: ["lwe", "lattices"],
    citations: ["kyber-2018", "frodokem-2017", "dvv-2019"],
    source_spec: null
  },
  {
    id: "encoding",
    title: "Encoding",
    subtitle: "How a real message becomes a lattice point — and how the decoder finds it again",
    category: "foundations",
    views: {
      simple:
        "Encoding is how a real message — a number, a key, a word — becomes a *lattice point* that the rest of the math can work with, and how the decoder gets the message back when the point arrives slightly nudged. Imagine the message as a stamped tile dropped into a wide grid. As long as no tile is dropped within bumping distance of another, you can always tell which tile is which, even if the wind has nudged every one of them an inch or two. Pick the spacing badly and a small breeze loses the message; pick it well and a small breeze is harmless. Most of the engineering in a KEM is choosing that spacing.",
      developer:
        "An encoding is a pair `(E, D)` where `E : M → L` embeds the message space `M` into the lattice `L`, and `D : L → M` recovers `m` when the received point is the lattice's nearest neighbour of `E(m) + e`. The end-to-end goal: for every `m ∈ M` and every error `e` from the noise budget, `D(E(m) + e) = m`. Common patterns: bit-by-bit modular encoding (early LWE schemes), Reed-Muller / Reed-Solomon codes layered on top of LWE noise, and lattice codes such as Barnes-Wall `BW_{2^k}` in `2^k` dimensions. Denser codes carry more bits per dimension but shrink the decoding radius — which is why encoding choices and noise parameters are tuned together, never separately.",
      researcher:
        "Let `L ⊂ R^n` be a lattice with minimum distance `λ₁(L)`, and let `M` be a finite message space. An encoder–decoder pair `(E, D)` satisfies the *recovery property* if for all `m ∈ M` and all `e` with `‖e‖ ≤ τ`, `D(E(m) + e) = m`, where `τ` is the *decoding radius*. The KEM's decryption-failure probability is `Pr_{e∼χ_total}[‖e_total‖ > τ]`, where `χ_total` is the convolution of LWE noise, key noise, and any rounding error. The design knob `(n, τ, |M|)` is what differentiates schemes: denser codes raise `|M|/n` but reduce `τ`, forcing tighter `χ` and altering the lattice-estimator output. Reed-Muller and Barnes-Wall codes (the Barnes-Wall family `BW_{2^k}`) are the dominant choices when the goal is to maximize `τ` per dimension; the `BW₃₂` instance used in S-Cloud+ (Wang et al., 2024) is one concrete realization of that strategy. Encoding choices are not orthogonal to the security argument — they enter the decryption-failure bound, which itself is attackable (D'Anvers et al., 2019)."
    },
    evidence_grade: "B",
    evidence_note:
      "Well-established design discipline: the encoder-decoder pair, the recovery property, and the failure-probability accounting are standard textbook material. Specific code choices (Reed-Muller vs. Barnes-Wall vs. bitwise) are an active engineering debate — graded B because the trade-off space is mature but not closed.",
    related: ["lwe", "noise", "lattices"],
    citations: ["scloud-plus-2024", "dvv-2019"],
    attack_links: [],
    source_spec: null
  },
  {
    id: "reconciliation",
    title: "Reconciliation",
    subtitle: "Two parties holding 'almost the same number' agreeing on exactly the same key",
    category: "foundations",
    views: {
      simple:
        "When Alice and Bob run an LWE-style key exchange, they don't end up with the same key — they end up with two keys that are *close but not identical*. Reconciliation is the small extra trick that lets them agree on the exact same key without either of them revealing much about their secret. The classic move: one party sends a few rounding hints — just enough to nudge the other party's near-match into the right bucket. With the hints, they end up identical; without them, they would be one bit apart and every encryption built on top would silently fail.",
      developer:
        "Reconciliation takes two near-equal lattice points `v_A ≈ v_B` (one held by each party after a KEM round) and outputs a shared, exact key. Two dominant patterns: **(1) helper-bit reconciliation** (NewHope, BLISS): Alice publishes a short hint `h` derived from `v_A`, and Bob applies `Rec(v_B, h) = k` such that `Rec(v_A, h) = k` too. **(2) encryption-style** (Kyber/ML-KEM, Saber): the shared 'key' is embedded directly via a message encoding, and reconciliation collapses into the encoding's recovery property — the hint disappears into the [encoding](#/encoding) layer. Modern KEMs increasingly favor (2) because helper bits leak some structure of the noise; (1) survives where every byte of bandwidth matters.",
      researcher:
        "Given two lattice points `v_A, v_B ∈ Z_q^n` with `v_A − v_B = e` for noise `e` bounded by `‖e‖ ≤ τ`, the reconciliation problem is to produce a public hint `h` and a function `Rec` such that `Rec(v_A, h) = Rec(v_B, h) = k` for a shared `k ∈ {0,1}^λ`, where the conditional distribution of `k` given `h` carries negligible additional information about Alice's secret beyond what is already exposed by `v_A`. The NewHope construction uses Voronoi-cell-style hint bits (Ding 2012; Peikert 2014; Alkim–Ducas–Pöppelmann–Schwabe 2016) tuned so that `h` is one bit per coefficient at the cost of slightly tighter `χ`. The encryption-style approach (Kyber, ML-KEM) instead embeds a uniform `k` directly via the encoder and lets the encoding's recovery property carry the agreement — the hint is replaced by the structure of the code (cf. [Encoding](#/encoding)). The two approaches differ in how leakage to a passive attacker is quantified: helper bits add a term to the lattice estimator; encryption-style approaches roll the leakage into the standard decryption-failure analysis. Hardware constraints can flip the choice — embedded targets sometimes prefer (1) for its smaller transcript at fixed security."
    },
    evidence_grade: "B",
    evidence_note: "Mature design space; both patterns are deployed in published / standardized KEMs. The trade-off (helper bits vs. encoding-embedded) is well-understood but actively re-litigated as standards evolve.",
    related: ["lwe", "encoding", "noise", "lattices"],
    citations: ["ding-2012", "peikert-2014", "newhope-2016"],
    attack_links: [],
    source_spec: null
  },
  {
    id: "parameter-choices",
    title: "Parameter choices",
    subtitle: "How (n, q, χ) get tuned — the joint optimization of security, bandwidth, and correctness",
    category: "foundations",
    views: {
      simple:
        "Every cryptographic scheme is a balance. Choose parameters that make attacks too expensive — but not so heavy that legitimate users can't run them. In lattice cryptography, the main knobs are the *dimension* (how many numbers in the secret), the *modulus* (the clock size), and the *noise size* (how much imperfection you mix in). Turn them too low and the math is easy to break; too high and your keys won't fit in a network packet. The published standards — ML-KEM, FrodoKEM — represent particular guesses about where the right balance lives, and that balance is publicly auditable: every parameter set ships with a derivation showing why these specific numbers.",
      developer:
        "Parameter selection for an LWE-based KEM is the joint optimization of `(n, m, q, χ)` against three constraints: **(1) Security target `λ`** (typically 128 / 192 / 256 classical bits, or 64 / 96 / 128 quantum bits under core-SVP), enforced via the lattice-estimator's output. **(2) Decryption-failure target `δ`** (typically `≤ 2^{-λ_sec}` per the D'Anvers et al. (2019) adaptive-failure bound). **(3) Bandwidth/latency envelope** (public-key size, ciphertext size, ops/sec). The trade is non-monotone: raising `n` raises security *and* bandwidth; tightening `χ` lowers `δ` but can lower security; raising `q` gives noise budget but inflates keys. ML-KEM-512 (Kyber) lives at one point in this triangle; FrodoKEM-640 at another. Choosing between them is choosing a position — not finding a unique answer.",
      researcher:
        "The methodology underlying every modern lattice-KEM parameter set: pick a candidate `(n, m, q, χ)`; run the *lattice estimator* (Albrecht, Player, Scott 2015 and the actively-maintained successors at the `lattice-estimator` project) to produce a security cost in some cost model — `core-SVP` being the de facto standard, with `2^{0.292 β}` (classical) and `2^{0.265 β}` (quantum) as the canonical BKZ-block-size mapping. Verify the cost meets `λ`; convolve `χ` (Kyber's CBD_η, FrodoKEM's discrete-Gaussian-approximation table) to bound `δ` and verify the D'Anvers (2019) adaptive-failure constraint. Iterate. The estimator's output is itself a moving target — new lattice-reduction or sieving results (G6K, BDGL 2016) periodically tighten the bound, and a parameter set valid in 2024 may be downgraded in 2027. Hence the lab's [`sl-bench/sl-kem/INTERPRETATION.md`](https://github.com/systemslibrarian/structureless-labs/blob/main/sl-bench/sl-kem/README.md) rule: numbers without the methodology and cost-model assumptions are not a result."
    },
    evidence_grade: "B",
    evidence_note:
      "Well-established methodology; the lattice estimator and core-SVP cost model are the canonical reference points. The specific numerical bounds are graded B (not A) because they shift as cryptanalysis improves.",
    related: ["lwe", "noise", "encoding", "modular", "reconciliation"],
    citations: ["kyber-2018", "frodokem-2017", "dvv-2019", "albrecht-2015"],
    attack_links: [],
    source_spec: null
  },
  {
    id: "attacks",
    title: "Attacks",
    subtitle: "Three honest ways to break a lattice KEM (plus side-channels)",
    category: "foundations",
    views: {
      simple:
        "There are three honest ways to break a lattice KEM. First, find the secret *directly* by guessing or computing — the 'find the needle in a high-dimensional haystack' attack, made hard by big dimensions. Second, find a *close* secret that the math thinks is the right one — the 'closest vector' problem, and how almost all real attacks work in practice. Third, get the legitimate decoder to leak information by feeding it strange inputs and watching when it fails — the 'decryption-failure' attack, and the reason every modern scheme makes failure astronomically rare. None of these is a clever twist; they are systematic, named, and well-studied. A fourth family — *side channels* — lives in the implementation, not the math.",
      developer:
        "Three formal attack families against LWE-based KEMs, plus implementation hazards. **(1) Lattice attacks.** Embed LWE into a lattice; run BKZ block reduction with sieving subroutines. The 'primal' variant solves the unique-SVP instance (Kannan embedding); the 'dual' solves a related decisional problem. Cost modeled as `core-SVP` against the block size `β`. **(2) Combinatorial attacks.** BKW (Blum-Kalai-Wasserman) and variants — trade space for time; dominant only in narrow parameter regimes. **(3) Adaptive failure attacks** — D'Anvers, Vercauteren, Verbauwhede (2019) showed an adversary submitting chosen ciphertexts can learn which inputs cause decryption failure and recover the secret in time `~1/δ`. (1) sets parameter dimensions; (3) sets noise distributions; (2) is a sanity check. **Side-channels** (timing, power, EM, fault injection) target the *implementation* and require the Engineer persona's review, not the spec author's.",
      researcher:
        "The **primal attack** reduces LWE to unique-SVP via the Kannan embedding; standard cost is `core-SVP` with block size `β` chosen to satisfy the GSA root-Hermite condition. The **dual attack** reduces to a Short Integer Solution (SIS) instance and tests distinguishing advantage with `m^* ≥ m` samples; for some regimes, the dual is asymptotically tighter. Both run BKZ (Chen-Nguyen 2011 and successors) with sieving subroutines (BDGL 2016 classically; Grover-style for the quantum cost model). The lattice estimator (Albrecht-Player-Scott 2015) produces concrete cost figures that move with each cryptanalytic update. **Decryption-failure attacks** (D'Anvers et al. 2019, followed by Guo-Johansson 2021, Bindel-Schanck 2020) act as the floor under noise-distribution choice — modern schemes target `δ ≤ 2^{-160}` or tighter precisely to evade this family. **Side-channels** are out of scope for the formal security argument but require constant-time considerations (and where secrets flow through tabular sampling, replacement of Gaussian-discrete sampling with CBD sampling). The lab's `sl-attacklab` is where structural and (eventually) cryptanalytic findings are filed; [F-0001](https://github.com/systemslibrarian/structureless-labs/blob/main/sl-attacklab/findings/F-0001.md) / [F-0003](https://github.com/systemslibrarian/structureless-labs/blob/main/sl-attacklab/findings/F-0003.md) are examples of the structural variety, filed before any parameter set exists to cryptanalyze."
    },
    evidence_grade: "B",
    evidence_note:
      "Attack families and their canonical references are well-established; concrete attack costs are an active research area and graded B because they shift with new results.",
    related: ["lwe", "noise", "encoding", "reconciliation", "lattices"],
    citations: ["regev-2005", "dvv-2019", "albrecht-2015"],
    attack_links: [],
    source_spec: null
  },
  {
    id: "scloud-plus",
    title: "S-Cloud+",
    subtitle: "An unstructured-lattice KEM from Wang et al. (2024) — studied here, not endorsed",
    category: "constructions",
    views: {
      simple:
        "S-Cloud+ is a post-quantum KEM published in 2024 by Wang and collaborators. It is *one* example of a 'structureless lattice' design — meaning it relies on plain unstructured LWE without the extra algebraic structure (rings, modules) that some attacks specifically target. It also uses an unusual encoding (the Barnes-Wall BW₃₂ lattice code) and a standard Fujisaki-Okamoto transform for chosen-ciphertext-attack resistance. We study S-Cloud+ here because the lab's own `sl-kem` lives in the same conservative family, and understanding how someone else solved similar problems makes the lab's own design questions clearer. Important: **studying S-Cloud+ does not mean we are endorsing it for production, and it does not make `sl-kem` more trustworthy.**",
      developer:
        "S-Cloud+ (*Wang et al.*, ePrint [2024/1306](https://eprint.iacr.org/2024/1306)) is an unstructured-LWE KEM whose distinctive design choices are: **(a) ternary secret distribution** — secrets sampled from `{−1, 0, +1}^n` rather than a wider CBD range, which lowers ciphertext bandwidth without (per the authors' analysis) materially weakening LWE security in the chosen regime; **(b) Barnes-Wall BW₃₂ lattice encoding** — using the BW family in dimension 32 to maximize the decoder's decoding radius `τ` per dimension, lowering `δ` for a given noise budget; **(c) Fujisaki-Okamoto transform** in the standard Hofheinz-Hövelmanns-Kiltz form for IND-CCA2. The headline practical result (per the paper's tables): smaller keys than FrodoKEM at comparable claimed security, without taking on the algebraic ring structure of ML-KEM. This atlas page describes S-Cloud+ as a *study target*; a faithful TypeScript reimplementation exists at [crypto-lab-scloud-vault](https://github.com/systemslibrarian/crypto-lab-scloud-vault). Adopting S-Cloud+'s parameters into `sl-kem` is what [`sl-kem` D-0003](https://github.com/systemslibrarian/structureless-labs/blob/main/sl-kem/decisions/D-0003.md)'s adopt-by-reference framework permits — *with explicit attribution and non-endorsement*.",
      researcher:
        "Wang et al. (2024) instantiate the construction `pk = (A, b = A·s + e)` with `A ∈ Z_q^{m×n}` sampled via a deterministic seed-expander, `s` from a ternary `{−1,0,+1}^n` distribution, and `e` from a centered binomial. Encaps uses standard FO derandomization `(r, e', e'') ← H(μ ‖ H(pk))` and produces `(c_1 = A^T r + e', c_2 = b^T r + e'' + E_{BW_{32}}(μ))` where `E_{BW_{32}}` encodes the message into the Barnes-Wall lattice in dimension 32. The Barnes-Wall family `BW_{2^k}` is one of the dominant choices for KEMs that aim to maximize `τ` per dimension; `BW_{32}` reaches the Mordell minimum kissing-number bound for its dimension. The security argument inherits unstructured-LWE hardness (Regev 2005 and successors) with concrete parameters whose `λ` and `δ` are stated in the published spec. **The lab's relationship to S-Cloud+ is methodological-and-pedagogical only** — see [`sl-researchkit/decisions/D-0002`](https://github.com/systemslibrarian/structureless-labs/blob/main/sl-researchkit/decisions/D-0002.md). Atlas content describes the design; the lab borrows neither Wang et al.'s construction nor their credibility for `sl-kem`."
    },
    evidence_grade: "B",
    evidence_note:
      "S-Cloud+'s construction and parameters are published and cited; the security argument is the authors'. Grade B reflects strong public consensus (the paper has been on ePrint since 2024) without formal proof in this atlas. **This page is a study of someone else's published KEM. No security claim is made by Structureless Labs about S-Cloud+ or its parameters.**",
    related: ["lwe", "encoding", "noise", "lattices"],
    citations: ["scloud-plus-2024", "frodokem-2017"],
    attack_links: [],
    source_spec: null
  },
  {
    id: "modular",
    title: "Modular Arithmetic (mod q)",
    subtitle: "The clock that every lattice scheme lives on",
    category: "foundations",
    views: {
      simple:
        "Pick a number, say 17. Now agree that whenever you count past 17, you wrap back around to 0. That's all `(mod 17)` means — arithmetic on a clock face with 17 hours instead of 12. Every lattice cryptosystem lives on such a clock; the size of the clock is called `q`. Why bother? Because wrapping makes large numbers stay small, and small numbers are what computers (and noise distributions) actually work with. The clock is the box that keeps everything finite.",
      developer:
        "`a mod q` is the unique value in `{0, 1, …, q−1}` congruent to `a` modulo `q`. All LWE operations — matrix multiply, addition, comparison — happen in `Z_q`. Choice of `q` matters: it should be large enough that the noise `e` does not 'wrap around' and destroy the message structure, but small enough that operations remain efficient. Common choices: `q = 3329` (Kyber, a prime), `q = 8192` (Saber, a power of two — fast modular reduction but algebraic structure carries trade-offs). The arithmetic also defines the noise budget: rounding-style decoders typically tolerate `‖e‖_∞ < q/4`.",
      researcher:
        "The ring `Z_q = Z / qZ` is the ground ring for unstructured LWE; structured variants live in `R_q = Z_q[X] / (Φ(X))` for a cyclotomic polynomial `Φ`. The choice of `q` interacts with: (1) the *NTT-friendliness* of structured rings (Kyber's `q = 3329` was chosen so that 256-point NTT works directly over `Z_q`); (2) *modulus-switching* techniques that reduce `q` to lower bandwidth at a controlled noise cost; (3) the *core-SVP* security estimate, which is mildly sensitive to `log q / n`. Prime moduli vs. power-of-two moduli have an active design debate; both are deployed in current standards."
    },
    evidence_grade: "A",
    evidence_note:
      "The mathematical content is elementary and uncontested. Engineering choices about specific values of `q` are well-justified in the standards literature.",
    related: ["lwe", "noise"],
    source_spec: null
  }
];
