/* sl-atlas concept content — embedded for zero-build deployment.
   The same content is mirrored as JSON under ../content/ for tooling. */

window.SL_ATLAS_CONCEPTS = [
  {
    id: "lwe",
    title: "Learning With Errors",
    subtitle: "The hard problem at the heart of lattice cryptography",
    category: "foundations",
    views: {
      simple:
        "A puzzle made hard by adding small mistakes. Imagine someone hands you lots of almost-right answers to a math problem — each one off by a tiny, unknown nudge. With enough nudges, working backwards to the secret becomes practically impossible. That deliberate imperfection is the lock. Take it away and the puzzle dissolves into something a calculator could solve. This single idea — *make the linear problem noisy* — is the engine behind a whole family of post-quantum cryptography.",
      developer:
        "A linear system with noise added. You publish `(A, b)` where `b = A·s + e (mod q)`. `A` is a public random matrix. `s` is the secret vector. `e` is small random noise drawn from a bounded distribution. Recovering `s` from `(A, b)` is the hard problem your security rests on. **Strip the noise away** and it collapses to ordinary linear algebra — Gaussian elimination solves it in milliseconds. The noise is the lock; the modulus `q` sets the room the math lives in; the dimension `n` sets the difficulty.",
      researcher:
        "Given samples `(A, A·s + e mod q)` with `A ∈ Z_q^{m×n}` uniform, secret `s ∈ Z_q^n`, and error `e` drawn from a bounded distribution `χ`, recover `s`. **Decisional-LWE** asks instead to distinguish such samples from uniform over `Z_q^{m×n} × Z_q^m`. Hardness is parameterized by `(n, q, χ)`; concrete security estimates derive from the best known lattice-reduction (BKZ, sieving) and combinatorial (BKW, dual) attacks against those parameters. Worst-case to average-case reductions (Regev '05; Peikert '09; BLP+ '13) connect LWE to standard lattice problems (GapSVP, SIVP) under appropriate parameter regimes — a structural argument for confidence, not a proof of unbreakability."
    },
    interactive: "lwe-matrix",
    evidence_grade: "B",
    evidence_note:
      "Strong consensus across the lattice-crypto literature; the worst-case-to-average-case reductions are well-studied. Concrete security depends on continued cryptanalysis of the assumed parameters — graded 'strong evidence, not proven here.'",
    related: ["lattices", "noise", "modular"],
    source_spec: "../../sl-kem/spec/EXPLAINER-LWE.md"
  },
  {
    id: "lattices",
    title: "Lattices",
    subtitle: "Grids of points in high-dimensional space — and why they are hard",
    category: "foundations",
    views: {
      simple:
        "Imagine an infinite sheet of graph paper. The grid points are a *lattice* — a regular, evenly-spaced pattern of dots. Now imagine that same grid in three dimensions. Then in four hundred. The dots are still perfectly regular, but the patterns are no longer something you can picture. Find the dot nearest to a given target in 400 dimensions and you have just solved a problem that protects messages from quantum computers. The simplicity of the picture is what makes the difficulty so surprising: nothing about a grid *looks* hard, until the dimensions stack up.",
      developer:
        "A lattice is the set of all integer combinations of a fixed *basis* of vectors: `L = { a₁·b₁ + a₂·b₂ + … + aₙ·bₙ : aᵢ ∈ Z }`. Same lattice, different bases — and the difference matters: a *good* (short, near-orthogonal) basis makes problems easy, a *bad* (long, skewed) basis makes them hard. The public key in a lattice scheme is effectively a bad basis; the private key is a good one. The two canonical hard problems: **SVP** (shortest vector) and **CVP** (closest vector). Approximate versions of these, in high dimensions, are what concrete crypto rests on.",
      researcher:
        "A full-rank lattice `L ⊂ R^n` is a discrete additive subgroup generated by a basis `B = (b₁, …, bₙ)`. **SVP_γ**: given `B`, find `v ∈ L \\ {0}` with `‖v‖ ≤ γ · λ₁(L)`. **CVP_γ**: given `B` and target `t`, find `v ∈ L` with `‖v − t‖ ≤ γ · dist(t, L)`. **GapSVP_γ** and **SIVP_γ** are the standard worst-case problems used in reductions. The state-of-the-art attacks are BKZ-style block reduction with sieving subroutines; security estimates are produced by *lattice estimators* (e.g. the LWE-estimator), not by closed-form proofs. The cryptographic story: LWE-hardness reduces (worst-case to average-case) to GapSVP/SIVP, giving structural — not numerical — confidence."
    },
    evidence_grade: "A",
    evidence_note:
      "The mathematical definitions are standard and uncontested. The cryptographic hardness assumptions (GapSVP, SIVP at the parameter regimes we use) are well-studied but, like all hardness assumptions, not proven.",
    related: ["lwe", "noise"],
    source_spec: null
  },
  {
    id: "noise",
    title: "Noise",
    subtitle: "Small, deliberate imperfection — the cryptographic raw material",
    category: "foundations",
    views: {
      simple:
        "Noise here doesn't mean sound. It means a tiny random nudge added on purpose. In daily life, noise is the enemy — it makes signals harder to read. In lattice cryptography, noise is the *friend*: it is what makes the math hard for an attacker. The trick is to add just enough noise to lose the attacker, but not so much that the legitimate decoder cannot still recover the message. This careful balance — *enough but not too much* — is what most of the engineering in a scheme like Kyber is really about.",
      developer:
        "Noise is sampled from a bounded distribution `χ` (usually centered binomial or discrete Gaussian) and added to the equation `b = A·s + e`. The standard deviation `σ` is the central knob. Bigger `σ` → harder for an attacker, but also more *decryption failures*: legitimate decoders use an error-correcting structure to absorb the noise, and if `e` ever exceeds the absorption budget, decryption silently produces the wrong message. Modern schemes (Kyber, Saber, FrodoKEM) tune `(n, q, σ)` so that the decryption-failure probability is astronomically small (e.g. `≤ 2⁻¹⁶⁰`) *and* the LWE problem remains hard.",
      researcher:
        "Let `χ` be a discrete distribution over `Z` with sub-Gaussian parameter `σ`. The LWE distribution is `{(a, ⟨a,s⟩ + e mod q) : a ← U(Z_q^n), e ← χ}`. The relevant trade-off space is bounded by two constraints: (1) the *attacker's* problem must remain hard, formalized via lattice-estimator output against BKZ/sieving with cost models like `core-SVP`; (2) the *decoder's* failure probability `Pr[‖e_total‖_∞ > q/4]` (for a rounding-style decoder) must satisfy the cryptanalytic bound from decryption-failure attacks (D'Anvers et al., 2019). Choosing `χ` as a centered binomial `CBD_η` is preferred for constant-time sampling — Gaussian-discrete sampling has historically been a side-channel hazard."
    },
    evidence_grade: "B",
    evidence_note:
      "Mature engineering; concrete failure-probability bounds are well-understood. The 'enough noise / not too much' trade-off is actively re-evaluated as new attacks appear.",
    related: ["lwe", "lattices"],
    source_spec: null
  },
  {
    id: "modular",
    title: "Modular Arithmetic (mod q)",
    subtitle: "The clock that every lattice scheme lives on",
    category: "foundations",
    views: {
      simple:
        "Pick a number, say 17. Now agree that whenever you count past 17, you wrap back around to 0. That's all `(mod 17)` means — arithmetic on a clock face with 17 hours instead of 12. Every lattice cryptosystem lives on such a clock; the size of the clock is called `q`. Why bother? Because wrapping makes large numbers stay small, and small numbers are what computers (and noise distributions) actually work with. The clock is the box that keeps everything finite.",
      developer:
        "`a mod q` is the unique value in `{0, 1, …, q−1}` congruent to `a` modulo `q`. All LWE operations — matrix multiply, addition, comparison — happen in `Z_q`. Choice of `q` matters: it should be large enough that the noise `e` does not 'wrap around' and destroy the message structure, but small enough that operations remain efficient. Common choices: `q = 3329` (Kyber, a prime), `q = 8192` (Saber, a power of two — fast modular reduction but algebraic structure carries trade-offs). The arithmetic also defines the noise budget: rounding-style decoders typically tolerate `‖e‖_∞ < q/4`.",
      researcher:
        "The ring `Z_q = Z / qZ` is the ground ring for unstructured LWE; structured variants live in `R_q = Z_q[X] / (Φ(X))` for a cyclotomic polynomial `Φ`. The choice of `q` interacts with: (1) the *NTT-friendliness* of structured rings (Kyber's `q = 3329` was chosen so that 256-point NTT works directly over `Z_q`); (2) *modulus-switching* techniques that reduce `q` to lower bandwidth at a controlled noise cost; (3) the *core-SVP* security estimate, which is mildly sensitive to `log q / n`. Prime moduli vs. power-of-two moduli have an active design debate; both are deployed in current standards."
    },
    evidence_grade: "A",
    evidence_note:
      "The mathematical content is elementary and uncontested. Engineering choices about specific values of `q` are well-justified in the standards literature.",
    related: ["lwe", "noise"],
    source_spec: null
  }
];
