/* sl-atlas glossary — reference definitions, each linked to the concept that
   actually teaches the idea. Definitions are reminders, not substitutes: they
   deliberately compress, and the linked concept is the honest version.
   Validated by scripts/check-glossary.mjs (terms unique + non-empty, every
   `concept` id must exist in concepts.js). */

window.SL_ATLAS_GLOSSARY = [
  { term: "Lattice", definition: "The set of all integer combinations of a basis of vectors — a perfectly regular grid of points, in any number of dimensions.", concept: "lattices" },
  { term: "Basis", definition: "A set of vectors whose integer combinations generate a lattice. The same lattice has many bases; short near-orthogonal ones make computation easy, long skewed ones make it hard.", concept: "lattices" },
  { term: "Basis reduction", definition: "Transforming a bad basis into a better one for the same lattice. Exact in 2D (Lagrange-Gauss); approximate and exponentially expensive in high dimension (LLL, BKZ).", concept: "lattices" },
  { term: "SVP (shortest vector problem)", definition: "Given a basis, find the shortest nonzero vector in the lattice. One of the two canonical hard lattice problems.", concept: "lattices" },
  { term: "CVP (closest vector problem)", definition: "Given a basis and a target point, find the lattice point nearest the target. The problem most real attacks reduce to in practice.", concept: "lattices" },
  { term: "Babai round-off", definition: "The simplest CVP heuristic: write the target in basis coordinates, round each coordinate, map back. Works with a good basis; misses with a skewed one.", concept: "lattices" },
  { term: "Unimodular transform", definition: "A basis change with determinant ±1 (integer matrix, integer inverse). It changes the basis but provably not the lattice — the demo's Skew button is one.", concept: "lattices" },
  { term: "LWE (Learning With Errors)", definition: "The hard problem `b = A·s + e (mod q)`: recover the secret `s` from noisy random linear equations. The engine of lattice cryptography.", concept: "lwe" },
  { term: "Decisional LWE", definition: "The distinguishing variant: tell LWE samples apart from uniformly random ones. Equivalent in hardness to search LWE for the relevant parameters.", concept: "lwe" },
  { term: "Ring-LWE", definition: "LWE with polynomial-ring structure: one ring element stands in for an entire structured matrix, shrinking keys and enabling NTT-fast multiplication.", concept: "ring-module-lwe" },
  { term: "Module-LWE", definition: "The middle ground between plain LWE and Ring-LWE: a small matrix of ring elements. What ML-KEM actually rests on; security levels change by changing the rank k.", concept: "ring-module-lwe" },
  { term: "NTT (number-theoretic transform)", definition: "The finite-field FFT: multiplies ring polynomials in O(n log n). The reason structured lattice schemes are fast, and the reason q = 3329 was chosen.", concept: "ring-module-lwe" },
  { term: "Modulus (q)", definition: "The size of the arithmetic clock everything lives on. Large enough that noise stays small relative to it; small enough that keys stay compact.", concept: "modular" },
  { term: "Noise / error (e)", definition: "Small random values added on purpose to make the linear algebra hard. The security ingredient — and the thing the decoder must absorb.", concept: "noise" },
  { term: "CBD (centered binomial distribution)", definition: "The noise distribution of choice in modern KEMs: a few coin flips added and subtracted. Bounded, easy to analyze, and constant-time to sample.", concept: "noise" },
  { term: "Discrete Gaussian", definition: "The theoretically natural noise distribution. Historically hazardous to sample in constant time, which is why deployed schemes prefer CBD.", concept: "noise" },
  { term: "σ (noise width)", definition: "The standard deviation of the noise distribution — the central knob trading attacker difficulty against decryption-failure risk.", concept: "noise" },
  { term: "Encoding", definition: "How a message becomes a lattice point spaced widely enough that noise cannot push it into a neighbour — and how the decoder finds it again.", concept: "encoding" },
  { term: "Decoding radius (τ)", definition: "The largest noise the decoder is guaranteed to absorb. For the simple rounding decoder, about q/4 per coordinate.", concept: "encoding" },
  { term: "Barnes-Wall codes", definition: "A family of dense lattice codes (BW₃₂ in S-Cloud+) used to maximize decoding radius per dimension — more message bits for the same noise budget.", concept: "encoding" },
  { term: "Decryption failure (δ)", definition: "The probability that an honest decoder recovers the wrong message because noise overflowed the budget. Doubly load-bearing: correctness and attack surface.", concept: "decryption-failure" },
  { term: "Reconciliation", definition: "The trick that turns two almost-equal values held by two parties into exactly one shared key, without leaking the values.", concept: "reconciliation" },
  { term: "Helper bits", definition: "Public rounding hints published by one party so the other rounds to the same bucket — the classic reconciliation mechanism (NewHope).", concept: "reconciliation" },
  { term: "KEM (key encapsulation mechanism)", definition: "A primitive with one job: lock a fresh random key inside a ciphertext only the key-holder can open. Bulk encryption then proceeds symmetrically.", concept: "ml-kem" },
  { term: "Encapsulation / decapsulation", definition: "The two halves of a KEM: produce (ciphertext, shared key) against a public key; recover the shared key with the private key.", concept: "ml-kem" },
  { term: "ML-KEM", definition: "The NIST-standardized lattice KEM (FIPS 203, August 2024), formerly CRYSTALS-Kyber. Module-LWE with n = 256, q = 3329, rank k ∈ {2, 3, 4}.", concept: "ml-kem" },
  { term: "FrodoKEM", definition: "The conservative unstructured-LWE KEM: no ring structure, larger keys, fewer assumptions. The structural reference point for structure-free designs.", concept: "parameter-choices" },
  { term: "FO transform (Fujisaki-Okamoto)", definition: "The compiler from CPA-secure encryption to CCA-secure KEM: derandomize, then re-encrypt on decapsulation and reject implicitly on mismatch.", concept: "ml-kem" },
  { term: "Implicit rejection", definition: "On a bad ciphertext, output a pseudorandom key instead of an error — denying chosen-ciphertext attackers the failure signal they need.", concept: "ml-kem" },
  { term: "IND-CCA2", definition: "The standard security target for KEMs: indistinguishability against adversaries who can submit arbitrary ciphertexts for decapsulation.", concept: "hybrid-constructions" },
  { term: "Hybrid construction", definition: "Classical + post-quantum KEMs combined so the derived key survives unless both fall. The conservative deployment default (X25519+ML-KEM-768).", concept: "hybrid-constructions" },
  { term: "Ciphertext binding", definition: "Feeding both ciphertexts into the hybrid KDF alongside both secrets. Load-bearing: without it, combiners can lose IND-CCA (Giacon-Heuer-Poettering).", concept: "hybrid-constructions" },
  { term: "KDF (key derivation function)", definition: "A one-way function that turns secret material (plus context) into uniform keys. In hybrids, the point where the two components become one key.", concept: "hybrid-constructions" },
  { term: "BKZ", definition: "The workhorse lattice-reduction algorithm: repeatedly solves SVP in blocks of size β. Bigger β, better basis, exponentially more time.", concept: "attacks" },
  { term: "Block size (β)", definition: "BKZ's quality dial. Security estimates reduce to \"what β does the attacker need?\" — then cost it via core-SVP.", concept: "attacks" },
  { term: "Sieving", definition: "The fastest known family of SVP subroutines inside BKZ, with cost ~2^0.292β classically and ~2^0.265β with quantum speedups.", concept: "attacks" },
  { term: "core-SVP", definition: "The deliberately conservative cost model behind most published estimates: count only 2^0.292β (classical) or 2^0.265β (quantum) per SVP call.", concept: "parameter-choices" },
  { term: "Lattice estimator", definition: "The maintained tool (Albrecht-Player-Scott lineage) that prices all known attacks against a parameter set. The authoritative source of concrete estimates.", concept: "parameter-choices" },
  { term: "Primal / dual attack", definition: "The two main lattice-reduction attack shapes: embed LWE as unique-SVP (primal), or distinguish via a short dual vector (dual).", concept: "attacks" },
  { term: "BKW", definition: "The combinatorial attack family that combines many samples to cancel structure — a sanity check on parameters rather than the usual winner.", concept: "attacks" },
  { term: "Side channel", definition: "Any physical signal of a computation — timing, power, EM, faults — that leaks secrets the mathematical model never exposed.", concept: "side-channels" },
  { term: "Constant-time programming", definition: "The implementation discipline that removes secret-dependent branches, memory addresses, and timing — the fix for timing side channels.", concept: "side-channels" },
  { term: "Masking", definition: "Splitting a secret into random shares so no single intermediate value reveals it — the standard defense against power analysis.", concept: "side-channels" },
  { term: "Shor's algorithm", definition: "The quantum algorithm that solves factoring and discrete logs in polynomial time — ending RSA and elliptic curves on a sufficiently large machine.", concept: "threat-model" },
  { term: "Grover's algorithm", definition: "The quantum search speedup: quadratic, provably optimal, poorly parallelizable. Halves symmetric security exponents rather than breaking them.", concept: "threat-model" },
  { term: "CRQC", definition: "Cryptographically relevant quantum computer — one large and reliable enough to run Shor's algorithm against deployed key sizes. None publicly exists.", concept: "threat-model" },
  { term: "Harvest now, decrypt later", definition: "Record encrypted traffic today; decrypt when a CRQC arrives. The reason post-quantum migration is a present-tense problem.", concept: "threat-model" },
  { term: "Mosca's inequality", definition: "If secrecy lifetime + migration time > time until a CRQC, you are already late. The planning rule that replaces hardware forecasting.", concept: "threat-model" },
  { term: "Evidence grade", definition: "The atlas's A-D label for how settled a concept's claims are — from well-established (A) to speculative (D). Every concept carries one, with a note explaining it.", concept: null }
];
